name: Build Caddy

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: Caddy version to build
        type: string
        default: latest
      xcaddy_version:
        description: xcaddy version
        type: string
        default: 0.3.2
      caddy_plugins:
        description: Caddy plugins to build with. Plugins are comma separated.
        type: string
        default: github.com/caddy-dns/cloudflare

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caddy GitHub repository
        uses: actions/checkout@v3.2.0
        with:
          repository: caddyserver/caddy
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: stable
          cache: true

      - name: Login to ghcr.io
        uses: redhat-actions/podman-login@v1.4
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Install xcaddy
        run: |
          curl -fsSL -o xcaddy.deb \
            https://github.com/caddyserver/xcaddy/releases/download/v${{ github.event.inputs.xcaddy_version }}/xcaddy_${{ github.event.inputs.xcaddy_version }}_linux_amd64.deb
          sudo apt install ./xcaddy.deb

      - name: Generate arguments for xcaddy
        uses: actions/github-script@v6.3.3
        id: build-flags
        with:
          result-encoding: string
          script: |
            const caddyVersion = context.payload.inputs.caddy_version;
            const caddyPlugins = context.payload.inputs.caddy_plugins;
            return `${caddyVersion} ${caddyPlugins
            	.split(',')
            	.map((plugin) => `--with ${plugin}`)
            	.join(' ')}`;

      - name: Generate Container tags
        uses: actions/github-script@v6.3.3
        id: container-tags
        with:
          result-encoding: string
          script: |
            const caddyPlugins = context.payload.inputs.caddy_plugins;
            return caddyPlugins
              .split(',')
              .map((plugin) => `with-plugin-${plugin.split('/').pop().replace('@', '-')}`)
              .join(' ');

      - name: Build Caddy with plugins
        run: xcaddy build ${{ steps.build-flags.outputs.result }}

      - name: Create Containerfile
        run: |
          cat <<'EOL' >Containerfile
          ARG CADDY_VERSION=latest

          FROM docker.io/caddy:${CADDY_VERSION}
          COPY ./caddy /usr/bin/caddy
          EOL

      - name: Build Container image
        id: build-container-image
        uses: redhat-actions/buildah-build@v2.10
        with:
          image: caddy
          tags: ${{ github.event.inputs.caddy_version }} ${{ steps.container-tags.outputs.result }}
          containerfiles: |
            ./Containerfile
          build-args: |
            CADDY_VERSION=${{ github.event.inputs.caddy_version }}

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.build-container-image.outputs.image }}
          tags: ${{ steps.build-container-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Upload built binary to workflow artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: caddy
          path: ./caddy
